### ISSUE TITLE
Ability to manually provide keys and random values

### ISSUE THREAD

**Issue by xpepermint** [enquo/cretrit#1]
Looks like I have the pleasure to open the first issue on this repository :). Below is my feature request.

I always want to have complete control over the execution of a program. This includes the ability to manually generate random numbers, keys, and such. I'm pretty scared of magic tricks that could be happening under the hood :).

Please add more options to create a `Cipher` object. Please allow us to manually provide `k1`, `k2`, and `seed`: [ref](https://github.com/enquo/cretrit/blob/main/src/cipher.rs#L40-L53) Generating random numbers is always my biggest concert and I try to grab the value from OS under "my own" conditions.

**Comment by mpalmer** [comment]
If you're not a fan of magic tricks, you're going to be all *sorts* of unhappy about ORE.  It's magic all the way down.  :grinning: 

A notation nit: cretrit doesn't have a `seed`, and I don't like "numbering" keys, because it can be hard to remember which one's which.  So `prf_key` and `prp_key` would be more appropriate.

I can think of a few ways of solving this; I'd be interested to know which would be better from your perspective (or if you've got another idea in mind):

1. create a `new_with_explicit_keys(prf_key: [u8; 16], prp_key: [u8; 16])` function.  This would seem to be the easiest, but it has a *massive* potential flaw: if a future CipherSuite happens to need more (or different) keys, we're totally screwed.  It'd also need more plumbing in the PRF and PRP traits, but that's a minor side point.  The main concern, for me, is the backwards-compatibility risk it creates.  I think I'd want to gate the function behind a feature flag, to prevent people from using it willy-nilly, and accepting that it might break in the future.
2. Make the KDF a trait, and provide a `new_with_kdf(kdf: dyn &KDF)` function.  That's... well, not future-proof, but at least it's your problem if a CipherSuite component needs a new key in the future, because you get to implement the extra key generator.
3. Create a `new_with_ciphersuite(prf: S::PRF, prp: S::PRP, r: S::RNG)` function, so that you can get the PRF and PRP (and RNG) however you want.  That'll make your code a bit more unwieldy, but it's the most future-proof approach, I think.  I'll need to split the PRF and PRP traits into two parts (for "init" and "exec") but that's a straightforward internal change.

If you can live with (3), I can roll a new release with that change fairly easily.  For (1) and (2) I'll want to have a bit more of a think about any other landmines before I roll ahead.

**Comment by xpepermint** [comment]
Number 3 should do the trick.

**Comment by mpalmer** [comment]
Cretrit 0.3.0 now rolling out to crates.io with `Cipher::new_with_ciphersuite` implemented.

**Comment by xpepermint** [comment]
Thx
